# syntax=docker/dockerfile:1.7

FROM ubuntu:24.04 AS dependencies

ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
ENV TZ=America/Mexico_City

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
    cmake git unzip build-essential ca-certificates curl zip tar \
    pkg-config ninja-build autoconf automake libtool glibc-tools \
    python3 mono-complete tzdata \
    && ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime \
    && echo "${TZ}" > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
COPY vcpkg.json /opt

RUN vcpkgCommitId=$(grep '.builtin-baseline' vcpkg.json | awk -F: '{print $2}' | tr -d '," ' | tr -d '\r\n') \
    && echo "vcpkg commit ID: '$vcpkgCommitId'" \
    && git clone https://github.com/microsoft/vcpkg.git \
    && cd vcpkg \
    && git fetch origin \
    && git checkout "$vcpkgCommitId" \
    && ./bootstrap-vcpkg.sh

WORKDIR /opt/vcpkg_manifest
COPY vcpkg.json /opt/vcpkg_manifest/

RUN --mount=type=cache,target=/opt/vcpkg/downloads,sharing=locked \
    --mount=type=cache,target=/opt/vcpkg/buildtrees,sharing=locked \
    --mount=type=cache,target=/opt/vcpkg/packages,sharing=locked \
    --mount=type=cache,target=/root/.cache/vcpkg,sharing=locked \
    /opt/vcpkg/vcpkg install \
      --x-manifest-root=/opt/vcpkg_manifest \
      --x-install-root=/opt/vcpkg_installed

FROM dependencies AS build

WORKDIR /srv/build
COPY src ./src
COPY cmake ./cmake
COPY recompile.sh CMakeLists.txt CMakePresets.json vcpkg.json ./
COPY --from=dependencies /opt/vcpkg_installed ./vcpkg_installed

ENV TERM=xterm

RUN cmake \
    -S . \
    -B build/linux-release \
    --preset linux-release \
    -DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake \
    -DVCPKG_MANIFEST_INSTALL=OFF \
    -DVCPKG_INSTALLED_DIR=/srv/build/vcpkg_installed \
    && cmake --build build/linux-release --parallel 2

FROM ubuntu:24.04 AS prod

COPY --from=build /srv/build/build/linux-release/bin/crystalserver /bin/crystalserver

WORKDIR /srv/olmeraot
ENTRYPOINT ["/srv/olmeraot/start.sh", "crystalserver"]
