name: olmeraot-dev

services:
  database:
    container_name: mysql-olmeraot-dev
    image: mariadb:11.4
    restart: unless-stopped
    env_file:
      - .env.dev
    networks:
      - olmeraot-dev-net
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - olmeraot-dev-db:/var/lib/mysql
      - ../schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    container_name: olmeraot-dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: prod
    restart: unless-stopped
    env_file:
      - .env.dev
    networks:
      - olmeraot-dev-net
    ports:
      - "${OT_SERVER_GAME_PORT}:${OT_SERVER_GAME_PORT}"
      - "${OT_SERVER_STATUS_PORT}:${OT_SERVER_STATUS_PORT}"
    volumes:
      - ../:/srv/olmeraot
    depends_on:
      database:
        condition: service_healthy

volumes:
  olmeraot-dev-db:

networks:
  olmeraot-dev-net:
    driver: bridge
